GLOBAL_LIST_INIT(familiar_types, list(
				"Pondstone Toad" = /mob/living/simple_animal/pet/familiar/pondstone_toad,
				"Mist Lynx" = /mob/living/simple_animal/pet/familiar/mist_lynx,
				"Rune Rat" = /mob/living/simple_animal/pet/familiar/rune_rat,
				"Vaporroot Wisp" = /mob/living/simple_animal/pet/familiar/vaporroot_wisp,
				"Ashcoiler" = /mob/living/simple_animal/pet/familiar/ashcoiler,
				"Glimmer Hare" = /mob/living/simple_animal/pet/familiar/glimmer_hare,
				"Hollow Antlerling" = /mob/living/simple_animal/pet/familiar/hollow_antlerling,
				"Mouse (brown)" = /mob/living/simple_animal/pet/familiar/mouse_brown,
				"Mouse (white)" = /mob/living/simple_animal/pet/familiar/mouse_white,
				"Mouse (grey)" = /mob/living/simple_animal/pet/familiar/mouse_grey,
				"Zad" = /mob/living/simple_animal/pet/familiar/crow,
				"Chicken (grey)" = /mob/living/simple_animal/pet/familiar/chicken_grey,
				"Chicken (brown)" = /mob/living/simple_animal/pet/familiar/chicken_brown,
				"Chicken (white)" = /mob/living/simple_animal/pet/familiar/chicken_white,
				"Chicken (black)" = /mob/living/simple_animal/pet/familiar/chicken_black,
				"Rat" = /mob/living/simple_animal/pet/familiar/rat,
				"Bat" = /mob/living/simple_animal/pet/familiar/bat,
				"Frog (Green)" = /mob/living/simple_animal/pet/familiar/frog_green,
				"Frog (Purple)" = /mob/living/simple_animal/pet/familiar/frog_purple,
				"Parrot" = /mob/living/simple_animal/pet/familiar/parrot,
				"Snake" = /mob/living/simple_animal/pet/familiar/snake,
				"Mudcrab" = /mob/living/simple_animal/pet/familiar/mudcrab,
				"Cat (Pink)" = /mob/living/simple_animal/pet/familiar/cat_pink,
				"Cat (Black)" = /mob/living/simple_animal/pet/familiar/cat_black,
				"Brass Thrum" = /mob/living/simple_animal/pet/familiar/mechanical/brass_thrum,
				"Gemspire Beetle" = /mob/living/simple_animal/pet/familiar/mechanical/gemspire_beetle,
				"Gravemoss Serpent" = /mob/living/simple_animal/pet/familiar/gravemoss_serpent,
				"Starfield Zad" = /mob/living/simple_animal/pet/familiar/starfield_crow,
				"Emberdrake" = /mob/living/simple_animal/pet/familiar/emberdrake,
				"Ripplefox" = /mob/living/simple_animal/pet/familiar/ripplefox,
				"Whisper Stoat" = /mob/living/simple_animal/pet/familiar/whisper_stoat,
				"Thornback Turtle" = /mob/living/simple_animal/pet/familiar/thornback_turtle
))

GLOBAL_LIST_INIT(familiar_display_names, list(
    /mob/living/simple_animal/pet/familiar/pondstone_toad = "Pondstone Toad",
    /mob/living/simple_animal/pet/familiar/mist_lynx = "Mist Lynx",
    /mob/living/simple_animal/pet/familiar/rune_rat = "Rune Rat",
    /mob/living/simple_animal/pet/familiar/vaporroot_wisp = "Vaporroot Wisp",
    /mob/living/simple_animal/pet/familiar/ashcoiler = "Ashcoiler",
    /mob/living/simple_animal/pet/familiar/glimmer_hare = "Glimmer Hare",
    /mob/living/simple_animal/pet/familiar/hollow_antlerling = "Hollow Antlerling",
    /mob/living/simple_animal/pet/familiar/gravemoss_serpent = "Gravemoss Serpent",
    /mob/living/simple_animal/pet/familiar/starfield_crow = "Starfield Zad",
    /mob/living/simple_animal/pet/familiar/emberdrake = "Emberdrake",
    /mob/living/simple_animal/pet/familiar/ripplefox = "Ripplefox",
    /mob/living/simple_animal/pet/familiar/whisper_stoat = "Whisper Stoat",
    /mob/living/simple_animal/pet/familiar/thornback_turtle = "Thornback Turtle",
    /mob/living/simple_animal/pet/familiar/mouse_brown = "Mouse",
    /mob/living/simple_animal/pet/familiar/mouse_white = "Mouse",
    /mob/living/simple_animal/pet/familiar/mouse_grey = "Mouse",
    /mob/living/simple_animal/pet/familiar/crow = "Zad",
    /mob/living/simple_animal/pet/familiar/chicken_grey = "Chicken",
    /mob/living/simple_animal/pet/familiar/chicken_brown = "Chicken",
    /mob/living/simple_animal/pet/familiar/chicken_white = "Chicken",
    /mob/living/simple_animal/pet/familiar/chicken_black = "Chicken",
    /mob/living/simple_animal/pet/familiar/rat = "Rat",
    /mob/living/simple_animal/pet/familiar/bat = "Bat",
    /mob/living/simple_animal/pet/familiar/frog_green = "Frog",
    /mob/living/simple_animal/pet/familiar/frog_purple = "Frog",
    /mob/living/simple_animal/pet/familiar/parrot = "Parrot",
    /mob/living/simple_animal/pet/familiar/snake = "Snake",
    /mob/living/simple_animal/pet/familiar/mudcrab = "Mudcrab",
    /mob/living/simple_animal/pet/familiar/cat_pink = "Cat",
    /mob/living/simple_animal/pet/familiar/cat_black = "Cat",
    /mob/living/simple_animal/pet/familiar/mechanical/brass_thrum = "Brass Thrum",
    /mob/living/simple_animal/pet/familiar/mechanical/gemspire_beetle = "Gemspire Beetle"
))

GLOBAL_LIST_INIT(familiar_lore_blurbs, list(
    /mob/living/simple_animal/pet/familiar/pondstone_toad = "Pondstone Toads are ancient, patient creatures, said to carry the wisdom of the marshes. They are calm, resilient, and often serve as silent observers.",
    /mob/living/simple_animal/pet/familiar/mist_lynx = "Mist Lynxes are elusive and mysterious, moving unseen through fog and shadow. They are clever, perceptive, and fiercely loyal to those they trust.",
    /mob/living/simple_animal/pet/familiar/rune_rat = "Rune Rats are quick-witted and curious, always seeking knowledge. They are drawn to secrets and the written word, leaving trails of glowing runes wherever they go.",
    /mob/living/simple_animal/pet/familiar/vaporroot_wisp = "Vaporroot Wisps are gentle spirits of mist and healing. They drift quietly, bringing calm and comfort to those around them.",
    /mob/living/simple_animal/pet/familiar/ashcoiler = "Ashcoilers are serpents born of long-forgotten hearth fires and latent magic. Patient and enduring, their presence brings resilience.",
    /mob/living/simple_animal/pet/familiar/glimmer_hare = "Glimmer Hares are quick and elusive, their bodies shimmering with light. They are symbols of luck and agility, always a step ahead of danger.",
    /mob/living/simple_animal/pet/familiar/hollow_antlerling = "Hollow Antlerlings are gentle forest spirits, symbols of luck and renewal. They are playful, curious, and bring fortune to their companions.",
    /mob/living/simple_animal/pet/familiar/gravemoss_serpent = "Gravemoss Serpents are ancient guardians of the earth, their scales flecked with lichen and grave-dust. They are wise, patient, and deeply connected to the cycle of life and death.",
    /mob/living/simple_animal/pet/familiar/starfield_crow = "Starfield Crows are mysterious and intelligent, their feathers shimmering with constellations. They are omens of fate and keepers of secrets.",
    /mob/living/simple_animal/pet/familiar/emberdrake = "Emberdrakes are tiny dragons of warmth and memory. Their presence stirs old stories and brings comfort in the darkest nights.",
    /mob/living/simple_animal/pet/familiar/ripplefox = "Ripplefoxes are tricksters and guides, flickering at the edge of sight. They are masters of illusion and always seem to know more than they let on.",
    /mob/living/simple_animal/pet/familiar/whisper_stoat = "Whisper Stoats are subtle and insightful, listening to thoughts and secrets. They are trusted confidants and clever companions.",
    /mob/living/simple_animal/pet/familiar/thornback_turtle = "Thornback Turtles are sturdy guardians, embodying endurance and protection. They are slow to anger but steadfast in defense of their friends.",

    // Mundane familiars
    /mob/living/simple_animal/pet/familiar/mouse_brown = "A small mouse, quick and alert, always searching for crumbs and cozy hiding spots.",
    /mob/living/simple_animal/pet/familiar/mouse_white = "A small mouse, quick and alert, always searching for crumbs and cozy hiding spots.",
    /mob/living/simple_animal/pet/familiar/mouse_grey = "A small mouse, quick and alert, always searching for crumbs and cozy hiding spots.",
    /mob/living/simple_animal/pet/familiar/crow = "A clever black crow, watchful and resourceful, known for its sharp eyes and love of shiny things.",
    /mob/living/simple_animal/pet/familiar/chicken_grey = "A chicken, lively and sociable, always scratching for seeds and insects.",
    /mob/living/simple_animal/pet/familiar/chicken_brown = "A chicken, lively and sociable, always scratching for seeds and insects.",
    /mob/living/simple_animal/pet/familiar/chicken_white = "A chicken, lively and sociable, always scratching for seeds and insects.",
    /mob/living/simple_animal/pet/familiar/chicken_black = "A chicken, lively and sociable, always scratching for seeds and insects.",
    /mob/living/simple_animal/pet/familiar/rat = "A streetwise rat, clever and adaptable, able to thrive in almost any environment.",
    /mob/living/simple_animal/pet/familiar/bat = "A tiny bat, nocturnal and swift, flitting silently through the night in search of insects.",
    /mob/living/simple_animal/pet/familiar/frog_green = "A green frog, cheerful and spry, happiest near water and quick to leap away from danger.",
    /mob/living/simple_animal/pet/familiar/frog_purple = "A purple frog, unusual in color but otherwise a typical amphibian, fond of damp places.",
    /mob/living/simple_animal/pet/familiar/parrot = "A bright parrot, talkative and intelligent, with a fondness for mimicking voices and sounds.",
    /mob/living/simple_animal/pet/familiar/snake = "A slender snake, calm and observant, moving gracefully and silently through its surroundings.",
    /mob/living/simple_animal/pet/familiar/mudcrab = "A mudcrab, sturdy and stubborn, scuttling sideways and always ready to defend itself.",
    /mob/living/simple_animal/pet/familiar/cat_pink = "A hairless cat, playful and affectionate, with a knack for finding the warmest spot in any room.",
    /mob/living/simple_animal/pet/familiar/cat_black = "A black cat, sleek and mysterious, often seen watching quietly from the shadows.",

    // Mechanical familiars
    /mob/living/simple_animal/pet/familiar/mechanical/brass_thrum = "A mechanical spider-like creature of brass and whirring gears, its movements precise and accompanied by a faint, rhythmic hum.",
    /mob/living/simple_animal/pet/familiar/mechanical/gemspire_beetle = "A four-legged, spider-like automaton adorned with crystalline spires, blending arcane energy with intricate clockwork."
))
